---
abstract: 'Perl extension for Trivial File Transfer Protocol Server'
author:
  - 'Luigino Masarati <lmasarati@hotmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-TFTPd
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.10
